In [40]:
"""
Sequence Prediction using LSTMs

Given 5 concecutive numbers, predict the next one.
I used an LSTM unit with a fully connected feed-forward network at the end, because LSTM only outputs in a smaller range

I will try to play around with
- batch_size (1, 5, 10, 20)
- Dense layer width (1, 3, 5, 10)
- optimizer ('adam', 'rmsprop')
- loss ('mean_squared_error', 'mean_absolute_error', 'mean_absolute_percentage_error')
"""

"\nSequence Prediction using LSTMs\n\nGiven 5 concecutive numbers, predict the next one.\nI used an LSTM unit with a fully connected feed-forward network at the end, because LSTM only outputs in a smaller range\n\nI will try to play around with\n- batch_size (1, 5, 10, 20)\n- Dense layer width (1, 3, 5, 10)\n- optimizer ('adam', 'rmsprop')\n- loss ('mean_squared_error', 'mean_absolute_error', 'mean_absolute_percentage_error')\n"

In [41]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Activation

import numpy as np

# create training, validation and testing datasets

x_train = [] # (examples * timestep * input_dim)
y_train = [] # (examples * input_dim)
for example in range(10000):
    temp = np.random.random()*100
    x_train.append([[temp], [temp+1], [temp+2], [temp+3], [temp+4]])
    y_train.append([temp+5])
    
x_val = [] # (examples * timestep * input_dim)
y_val = [] # (examples * input_dim)
for example in range(80):
    temp = np.random.random()*100
    x_val.append([[temp], [temp+1], [temp+2], [temp+3], [temp+4]])
    y_val.append([temp+5])

x_test = []
for example in range(20): # one batch for testing
    x_test.append([[example], [example+1], [example+2], [example+3], [example+4]])

x_test = np.array(x_test)
x_train = np.array(x_train)
x_val = np.array(x_val)
y_train = np.array(y_train)
y_val = np.array(y_val)

In [42]:
def create_model(batch_size, dense_width, optimizer, loss):
    timesteps = 5
    input_dim = 1

    model = Sequential()
    model.add(LSTM(1, batch_input_shape=(batch_size, timesteps, input_dim))) #(batch_size, timesteps, input_dim)
    # added a hidden layer on top because of the large range of values expected 
    model.add(Dense(dense_width))
    model.add(Dense(1))

    model.compile(loss=loss,
              optimizer=optimizer) # we skipped metrics
    
    return model

In [44]:
batch_sizes = (1, 5, 10, 20)
dense_widths = (1, 3, 5, 10)
optimizers = ('adam', 'rmsprop')
loss = ('mean_squared_error', 'mean_absolute_error', 'mean_absolute_percentage_error')

batch_size = 1
model1 = create_model(1, 1, 'adam', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 122s 12ms/step - loss: 1366.3737 - val_loss: 701.0871
Epoch 2/20
10000/10000 [==============================] - 122s 12ms/step - loss: 841.0251 - val_loss: 707.1400
Epoch 3/20
10000/10000 [==============================] - 112s 11ms/step - loss: 841.0390 - val_loss: 700.5072
Epoch 4/20
10000/10000 [==============================] - 117s 12ms/step - loss: 841.0732 - val_loss: 701.0979
Epoch 5/20
10000/10000 [==============================] - 109s 11ms/step - loss: 840.5913 - val_loss: 710.0008
Epoch 6/20
10000/10000 [==============================] - 110s 11ms/step - loss: 841.1693 - val_loss: 707.3729
Epoch 7/20
10000/10000 [==============================] - 117s 12ms/step - loss: 841.2069 - val_loss: 704.4916
Epoch 8/20
10000/10000 [==============================] - 151s 15ms/step - loss: 840.9714 - val_loss: 706.0190
Epoch 9/20
10000/10000 [==============================] - 160s 1

KeyboardInterrupt: 

In [45]:
batch_size = 20
model1 = create_model(batch_size, 1, 'adam', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 7s 701us/step - loss: 3725.7585 - val_loss: 3643.4198
Epoch 2/20
10000/10000 [==============================] - 6s 580us/step - loss: 3254.2169 - val_loss: 3023.3349
Epoch 3/20
10000/10000 [==============================] - 6s 593us/step - loss: 2598.3104 - val_loss: 2294.2261
Epoch 4/20
10000/10000 [==============================] - 6s 578us/step - loss: 1915.4068 - val_loss: 1605.2394
Epoch 5/20
10000/10000 [==============================] - 6s 581us/step - loss: 1315.8963 - val_loss: 1041.9621
Epoch 6/20
10000/10000 [==============================] - 6s 582us/step - loss: 848.4874 - val_loss: 633.9693
Epoch 7/20
10000/10000 [==============================] - 6s 587us/step - loss: 515.6396 - val_loss: 365.0637
Epoch 8/20
10000/10000 [==============================] - 6s 588us/step - loss: 296.8917 - val_loss: 201.9478
Epoch 9/20
10000/10000 [==============================] - 6s 58

In [46]:
model1.predict(x_test)

array([[ 6.9220033],
       [ 7.7155104],
       [ 8.910839 ],
       [ 9.862392 ],
       [10.702709 ],
       [11.4645405],
       [12.226768 ],
       [12.977165 ],
       [13.743275 ],
       [14.524788 ],
       [15.321396 ],
       [16.132753 ],
       [16.958511 ],
       [17.798294 ],
       [18.651726 ],
       [19.518404 ],
       [20.397928 ],
       [21.289875 ],
       [22.193832 ],
       [23.109358 ]], dtype=float32)

In [47]:
batch_size = 10
model1 = create_model(batch_size, 1, 'adam', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 13s 1ms/step - loss: 3461.8290 - val_loss: 2978.1877
Epoch 2/20
10000/10000 [==============================] - 12s 1ms/step - loss: 2241.1067 - val_loss: 1628.4883
Epoch 3/20
10000/10000 [==============================] - 12s 1ms/step - loss: 1238.0906 - val_loss: 884.3429
Epoch 4/20
10000/10000 [==============================] - 12s 1ms/step - loss: 883.6022 - val_loss: 718.5299
Epoch 5/20
10000/10000 [==============================] - 12s 1ms/step - loss: 841.7996 - val_loss: 703.3144
Epoch 6/20
10000/10000 [==============================] - 13s 1ms/step - loss: 840.5288 - val_loss: 704.8948
Epoch 7/20
10000/10000 [==============================] - 12s 1ms/step - loss: 840.7133 - val_loss: 703.7210
Epoch 8/20
10000/10000 [==============================] - 12s 1ms/step - loss: 840.6677 - val_loss: 703.0326
Epoch 9/20
10000/10000 [==============================] - 12s 1ms/step - los

In [49]:
model1.predict(x_test[:10])

array([[55.153145],
       [55.153145],
       [55.153145],
       [55.153145],
       [55.153145],
       [55.153145],
       [55.153145],
       [55.153145],
       [55.153145],
       [55.153145]], dtype=float32)

In [51]:
batch_size = 10
model1 = create_model(batch_size, 1, 'rmsprop', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 12s 1ms/step - loss: 3534.3033 - val_loss: 3166.2296
Epoch 2/20
10000/10000 [==============================] - 11s 1ms/step - loss: 2426.6329 - val_loss: 1741.4872
Epoch 3/20
10000/10000 [==============================] - 11s 1ms/step - loss: 1109.3155 - val_loss: 542.7611
Epoch 4/20
10000/10000 [==============================] - 11s 1ms/step - loss: 260.2663 - val_loss: 60.6958
Epoch 5/20
10000/10000 [==============================] - 13s 1ms/step - loss: 29.1671 - val_loss: 16.9200
Epoch 6/20
10000/10000 [==============================] - 13s 1ms/step - loss: 9.4853 - val_loss: 4.9907
Epoch 7/20
10000/10000 [==============================] - 12s 1ms/step - loss: 6.1553 - val_loss: 4.2110
Epoch 8/20
10000/10000 [==============================] - 11s 1ms/step - loss: 4.9366 - val_loss: 3.1286
Epoch 9/20
10000/10000 [==============================] - 11s 1ms/step - loss: 3.7030 - val

In [52]:
model1.predict(x_test[:10])

array([[ 6.650261 ],
       [ 6.7518044],
       [ 7.6232786],
       [ 8.475551 ],
       [ 9.325229 ],
       [10.181229 ],
       [11.0598545],
       [11.970317 ],
       [12.914243 ],
       [13.888126 ]], dtype=float32)

In [53]:
batch_size = 10
model1 = create_model(batch_size, 3, 'rmsprop', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 13s 1ms/step - loss: 3353.8938 - val_loss: 2831.6121
Epoch 2/20
10000/10000 [==============================] - 12s 1ms/step - loss: 2037.2292 - val_loss: 1310.1888
Epoch 3/20
10000/10000 [==============================] - 12s 1ms/step - loss: 782.3835 - val_loss: 248.8471
Epoch 4/20
10000/10000 [==============================] - 12s 1ms/step - loss: 85.7574 - val_loss: 6.4520
Epoch 5/20
10000/10000 [==============================] - 12s 1ms/step - loss: 4.4110 - val_loss: 3.0019
Epoch 6/20
10000/10000 [==============================] - 12s 1ms/step - loss: 2.8326 - val_loss: 6.4993
Epoch 7/20
10000/10000 [==============================] - 12s 1ms/step - loss: 2.5485 - val_loss: 1.7248
Epoch 8/20
10000/10000 [==============================] - 12s 1ms/step - loss: 2.4215 - val_loss: 0.4524
Epoch 9/20
10000/10000 [==============================] - 12s 1ms/step - loss: 2.3647 - val_loss

In [54]:
model1.predict(x_test[:10])

array([[ 4.3492937],
       [ 6.6462154],
       [ 7.57467  ],
       [ 7.9102955],
       [ 8.607642 ],
       [ 9.564816 ],
       [10.595474 ],
       [11.641147 ],
       [12.688025 ],
       [13.731581 ]], dtype=float32)

In [55]:
batch_size = 10
model1 = create_model(batch_size, 3, 'rmsprop', 'mean_absolute_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 13s 1ms/step - loss: 52.2679 - val_loss: 50.9538
Epoch 2/20
10000/10000 [==============================] - 12s 1ms/step - loss: 43.5758 - val_loss: 39.8384
Epoch 3/20
10000/10000 [==============================] - 12s 1ms/step - loss: 32.6383 - val_loss: 27.5112
Epoch 4/20
10000/10000 [==============================] - 12s 1ms/step - loss: 21.8242 - val_loss: 15.5005
Epoch 5/20
10000/10000 [==============================] - 12s 1ms/step - loss: 11.9216 - val_loss: 7.5520
Epoch 6/20
10000/10000 [==============================] - 12s 1ms/step - loss: 6.7448 - val_loss: 4.1973
Epoch 7/20
10000/10000 [==============================] - 12s 1ms/step - loss: 4.2141 - val_loss: 2.6901
Epoch 8/20
10000/10000 [==============================] - 12s 1ms/step - loss: 2.7822 - val_loss: 2.3130
Epoch 9/20
10000/10000 [==============================] - 12s 1ms/step - loss: 1.9511 - val_loss: 1.6549

In [56]:
model1.predict(x_test[:10])

array([[ 5.825353],
       [ 6.115031],
       [ 7.142874],
       [ 8.170712],
       [ 9.198555],
       [10.226398],
       [11.254238],
       [12.282081],
       [13.309918],
       [14.337771]], dtype=float32)

In [57]:
batch_size = 10
model1 = create_model(batch_size, 3, 'rmsprop', 'mean_absolute_percentage_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 13s 1ms/step - loss: 91.7810 - val_loss: 84.5428
Epoch 2/20
10000/10000 [==============================] - 12s 1ms/step - loss: 72.9053 - val_loss: 66.1958
Epoch 3/20
10000/10000 [==============================] - 14s 1ms/step - loss: 59.1821 - val_loss: 52.3124
Epoch 4/20
10000/10000 [==============================] - 13s 1ms/step - loss: 47.3963 - val_loss: 41.5138
Epoch 5/20
10000/10000 [==============================] - 11s 1ms/step - loss: 38.1171 - val_loss: 32.3997
Epoch 6/20
10000/10000 [==============================] - 11s 1ms/step - loss: 31.3780 - val_loss: 25.5301
Epoch 7/20
10000/10000 [==============================] - 11s 1ms/step - loss: 25.8414 - val_loss: 20.4887
Epoch 8/20
10000/10000 [==============================] - 12s 1ms/step - loss: 21.0613 - val_loss: 15.6100
Epoch 9/20
10000/10000 [==============================] - 12s 1ms/step - loss: 16.9737 - val_loss

In [58]:
model1.predict(x_test[:10])

array([[ 6.131521 ],
       [ 1.5297997],
       [ 5.7418137],
       [ 8.760043 ],
       [10.622157 ],
       [11.715281 ],
       [12.423816 ],
       [13.14375  ],
       [13.874999 ],
       [14.6174345]], dtype=float32)

In [59]:
batch_size = 20
model1 = create_model(batch_size, 3, 'rmsprop', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 8s 769us/step - loss: 3765.8371 - val_loss: 3759.9611
Epoch 2/20
10000/10000 [==============================] - 6s 620us/step - loss: 3477.9806 - val_loss: 3387.0220
Epoch 3/20
10000/10000 [==============================] - 6s 595us/step - loss: 3064.8640 - val_loss: 2898.0142
Epoch 4/20
10000/10000 [==============================] - 6s 601us/step - loss: 2561.8160 - val_loss: 2338.0581
Epoch 5/20
10000/10000 [==============================] - 6s 604us/step - loss: 2016.9601 - val_loss: 1753.5058
Epoch 6/20
10000/10000 [==============================] - 6s 609us/step - loss: 1472.3209 - val_loss: 1198.8327
Epoch 7/20
10000/10000 [==============================] - 6s 624us/step - loss: 984.9798 - val_loss: 734.4315
Epoch 8/20
10000/10000 [==============================] - 6s 603us/step - loss: 593.3038 - val_loss: 397.1462
Epoch 9/20
10000/10000 [==============================] - 6s 

In [60]:
model1.predict(x_test)

array([[10.411889],
       [ 6.500748],
       [ 8.18046 ],
       [10.095548],
       [11.7875  ],
       [13.007392],
       [14.19679 ],
       [15.080066],
       [15.90831 ],
       [16.74871 ],
       [17.44182 ],
       [18.131783],
       [18.833862],
       [19.547955],
       [20.273989],
       [21.011871],
       [21.761494],
       [22.522728],
       [23.295464],
       [24.07959 ]], dtype=float32)

In [61]:
batch_size = 20
model1 = create_model(batch_size, 5, 'rmsprop', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 7s 712us/step - loss: 3749.1491 - val_loss: 3726.3110
Epoch 2/20
10000/10000 [==============================] - 6s 593us/step - loss: 3432.8285 - val_loss: 3326.6652
Epoch 3/20
10000/10000 [==============================] - 6s 611us/step - loss: 2997.9904 - val_loss: 2817.3040
Epoch 4/20
10000/10000 [==============================] - 7s 652us/step - loss: 2480.6929 - val_loss: 2246.9276
Epoch 5/20
10000/10000 [==============================] - 6s 606us/step - loss: 1940.4783 - val_loss: 1676.9810
Epoch 6/20
10000/10000 [==============================] - 6s 594us/step - loss: 1441.9607 - val_loss: 1181.5224
Epoch 7/20
10000/10000 [==============================] - 6s 609us/step - loss: 1065.8932 - val_loss: 845.3519
Epoch 8/20
10000/10000 [==============================] - 6s 609us/step - loss: 876.4664 - val_loss: 719.1664
Epoch 9/20
10000/10000 [==============================] - 6s

In [62]:
batch_size = 20
model1 = create_model(batch_size, 5, 'adam', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 8s 767us/step - loss: 3443.8512 - val_loss: 2908.6015
Epoch 2/20
10000/10000 [==============================] - 6s 616us/step - loss: 2340.4714 - val_loss: 1882.8275
Epoch 3/20
10000/10000 [==============================] - 6s 634us/step - loss: 1436.0368 - val_loss: 1039.9818
Epoch 4/20
10000/10000 [==============================] - 6s 631us/step - loss: 771.1772 - val_loss: 505.6567
Epoch 5/20
10000/10000 [==============================] - 7s 652us/step - loss: 371.7357 - val_loss: 226.2373
Epoch 6/20
10000/10000 [==============================] - 6s 644us/step - loss: 165.5306 - val_loss: 96.7724
Epoch 7/20
10000/10000 [==============================] - 6s 632us/step - loss: 70.5214 - val_loss: 39.3584
Epoch 8/20
10000/10000 [==============================] - 6s 631us/step - loss: 29.8746 - val_loss: 15.8172
Epoch 9/20
10000/10000 [==============================] - 6s 639us/step 

In [63]:
model1.predict(x_test)

array([[ 5.8057785],
       [ 6.229392 ],
       [ 6.9510884],
       [ 7.7992773],
       [ 8.747124 ],
       [ 9.764968 ],
       [10.823353 ],
       [11.8959465],
       [12.967245 ],
       [14.343191 ],
       [15.364664 ],
       [16.332373 ],
       [17.292048 ],
       [18.24866  ],
       [19.206987 ],
       [20.16764  ],
       [21.130926 ],
       [22.096886 ],
       [23.065252 ],
       [24.035507 ]], dtype=float32)

In [64]:
batch_size = 20
model1 = create_model(batch_size, 10, 'adam', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 9s 887us/step - loss: 3732.9408 - val_loss: 3656.6407
Epoch 2/20
10000/10000 [==============================] - 7s 736us/step - loss: 3268.5776 - val_loss: 3039.2592
Epoch 3/20
10000/10000 [==============================] - 7s 739us/step - loss: 2617.8923 - val_loss: 2319.1926
Epoch 4/20
10000/10000 [==============================] - 7s 662us/step - loss: 1958.9088 - val_loss: 1661.5996
Epoch 5/20
10000/10000 [==============================] - 6s 625us/step - loss: 1425.5089 - val_loss: 1175.8806
Epoch 6/20
10000/10000 [==============================] - 6s 635us/step - loss: 1082.3281 - val_loss: 890.0601
Epoch 7/20
10000/10000 [==============================] - 6s 624us/step - loss: 913.9705 - val_loss: 761.9338
Epoch 8/20
10000/10000 [==============================] - 6s 615us/step - loss: 855.7537 - val_loss: 717.9874
Epoch 9/20
10000/10000 [==============================] - 6s 6

In [65]:
batch_size = 20
model1 = create_model(batch_size, 10, 'adam', 'mean_squared_error')

model1.fit(x_train, y_train,
          batch_size=batch_size, epochs=20, shuffle=True,
          validation_data=(x_val, y_val))

Train on 10000 samples, validate on 80 samples
Epoch 1/20
10000/10000 [==============================] - 8s 790us/step - loss: 3737.4069 - val_loss: 3664.2297
Epoch 2/20
10000/10000 [==============================] - 6s 616us/step - loss: 3022.2925 - val_loss: 2302.5234
Epoch 3/20
10000/10000 [==============================] - 6s 618us/step - loss: 1712.9248 - val_loss: 1227.9031
Epoch 4/20
10000/10000 [==============================] - 6s 629us/step - loss: 894.7492 - val_loss: 583.3317
Epoch 5/20
10000/10000 [==============================] - 7s 651us/step - loss: 423.6468 - val_loss: 256.2576
Epoch 6/20
10000/10000 [==============================] - 6s 632us/step - loss: 186.0396 - val_loss: 107.6777
Epoch 7/20
10000/10000 [==============================] - 6s 631us/step - loss: 78.8239 - val_loss: 44.0609
Epoch 8/20
10000/10000 [==============================] - 6s 626us/step - loss: 33.6577 - val_loss: 18.3377
Epoch 9/20
10000/10000 [==============================] - 6s 644us/step

In [66]:
"""
Conclusions

As we can see, the results are not always consistent, but in general
More batches seems faster and more accurate (of course too many can also be a bad thing)
Adam and RMSProp seem to work fine, although Adam seemed to be slightly better (or more consistent)
Also a 3 unit wide layer seemed to be enough, whereas 5 was also working ok - one unit was not as good

Many times we had error to be ~700 which I guess is guessing the same number that is 
minimizing the squared error for the validation data - a local minimum
"""

'\nConclusions\n\nAs we can see, the results are not always consistent, but in general\nMore batches seems faster and more accurate (of course too many can also be a bad thing)\nAdam and RMSProp seem to work fine, although Adam seemed to be slightly better (or more consistent)\nAlso a 3 unit wide layer seemed to be enough, whereas 5 was also working ok - one unit was not as good\n\nMany times we had error to be ~700 which I guess is guessing the same number that is \nminimizing the squared error for the validation data - a local minimum\n'